import type { Metadata } from "next";
import "./globals.css";
import "react-skeletonify/dist/index.css";
import { Providers } from "@/components/shared/Providers";

export const metadata: Metadata = {
  title: "Skillseed",
  description: "Generated by Skillseed",
  icons: {
    icon: "/assets/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>{children}</Providers>
    </html>
  );
}

