

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-skeletonify/dist/index.css"; 
import { Providers } from "@/components/Providers"; 
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skillseed",
  description: "Generated by Skillseed",
  icons: {
    icon: "/assets/logo.png",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const session = await getServerSession(authOptions);
  console.log('session in layout',session)
  return (
    <html lang="en">
      {/* Fonts are applied via className in Providers now */}
      <Providers session={session}>{children}</Providers>
    </html>
  );
}
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import './globals.css'
// import "react-skeletonify/dist/index.css";
// import { Toaster } from "@/components/ui/sonner";
// import { SessionProvider } from "next-auth/react";
// import QueryProvider from "@/components/QueryProvider";
// import { SkeletonProvider } from "react-skeletonify";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//    title: "Skillseed",
//   description: "Generated by Skillseed",
//    icons: {
//     icon: "/assets/logo.png", 
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//          <SessionProvider>
//           <QueryProvider>
//             <SkeletonProvider
//               config={{
//                 background: 'hsl(var(--muted))',  // Matches your theme's muted color for skeletons
//                 animationSpeed: 1.5,  // Optional: Faster/slower animation (default: 1)
//                 // Add more config as needed, e.g., exceptTags: ['button'], borderRadius: 'var(--radius)'
//               }}
//             >
//               {children}
//             </SkeletonProvider>
//           </QueryProvider>
//           <Toaster richColors position="top-center" />
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }
